version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 530523547736.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - echo ***************************** DOCKER BUILDX local *****************************
      # - docker buildx build -t $IMAGE_REPO_NAME:$IMAGE_TAG . --platform linux/arm64
      # - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      # - docker images
      # - docker image inspect $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker build -t project3hiep .
      # - docker buildx build -t udacity-p03-ecr-repo . --platform linux/arm64
      - docker tag project3hiep:latest 530523547736.dkr.ecr.us-east-1.amazonaws.com/project3hiep:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push 530523547736.dkr.ecr.us-east-1.amazonaws.com/project3hiep:latest