version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: project3hiep
    
phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 337040204257.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | head -c 7)
  build:
    commands:
      - cd analytics
      - echo Starting build at `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 337040204257.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - IMAGE_URI=337040204257.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo $IMAGE_URI
      - docker push $IMAGE_URI
      - cd configurations
      - sed -i -e "s|<CONTAINER_IMAGE_NAME>|`echo ${IMAGE_URI}`|g" deployment.yaml
      - cat deployment.yaml