version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 530523547736.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...    
      - cd analytics
      - docker build -t project3hiep .
      - docker tag project3hiep:latest 530523547736.dkr.ecr.us-east-1.amazonaws.com/project3hiep:latest    
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push 530523547736.dkr.ecr.us-east-1.amazonaws.com/project3hiep:latest