version: 0.2

env:
  shell: /bin/sh

phases:
  # install:
  #   on-failure: ABORT
  #   runtime-versions:
  #     docker: 24
  pre_build:
    on-failure: ABORT
    commands:
      - echo Login ECR.
      - IMAGE_TAG=1.0.0
      - AWS_REPOSITORY="project3hiep"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 530523547736.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t project3hiep .
      - docker tag project3hiep:latest 530523547736.dkr.ecr.us-east-1.amazonaws.com/project3hiep:latest
  build:
    on-failure: ABORT
    commands:
      - docker push 530523547736.dkr.ecr.us-east-1.amazonaws.com/project3hiep:latest
