apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster-hiepnq
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.large
    desiredCapacity: 2
    volumeSize: 50
    amiFamily: Ubuntu2004
    ssh:
      allow: false

cloudWatch:
  clusterLogging:
    enableTypes:
      - "*"
    logRetentionInDays: 7

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
  - us-east-1f