apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          image: <CONTAINER_IMAGE_NAME>
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
            - containerPort: 5153
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-cm
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-cm
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-cm
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-password
