apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  labels:
    app: p3-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p3-app
  template:
    metadata:
      labels:
        app: p3-app
    spec:
      containers:
        - name: app-container
          image: 530523547736.dkr.ecr.us-east-1.amazonaws.com/project3hiep
          ports:
            - containerPort: 80
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: DB_NAME
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_PORT
            
